name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test -- --coverage
      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          directory: coverage
          fail_ci_if_error: true
          verbose: true
